.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. limracoin_qt test_limracoin_qt
clean: FORCE
	$(MAKE) -C .. limracoin_qt_clean test_limracoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_limracoin_qt_check
limracoin-qt limracoin-qt.exe: FORCE
	 $(MAKE) -C .. limracoin_qt
